-- Variant rows for mattresses / beds. Parent: public.beds(id).
-- API: routes/products.js → replaceBedVariants() inserts:
--   product_id, width, height, length, price
--
-- If this table already exists, compare columns/FK to below; fix FK target if it wrongly references another table.

CREATE TABLE IF NOT EXISTS public.product_variants_bed (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  product_id bigint NOT NULL,
  width integer NULL,
  height integer NULL,
  length integer NULL,
  price bigint NOT NULL,
  CONSTRAINT product_variants_bed_pkey PRIMARY KEY (id),
  CONSTRAINT product_variants_bed_product_id_fkey
    FOREIGN KEY (product_id)
    REFERENCES public.beds (id)
    ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_product_variants_bed_product_id
  ON public.product_variants_bed (product_id);
